import express from "express";
import doctorController from "../app/controllers/doctorsController.js";
import { authorizeRole } from "../app/middleware/authorize.js";
import { verifyToken } from "../app/middleware/verifyToken.js";
const router = express.Router();
router.get("/", doctorController.getAll);
router.get("/:id", doctorController.get);
router.post("/", verifyToken, authorizeRole(["manager", "doctor"]), doctorController.create);
router.put("/:id", verifyToken, authorizeRole(["manager", "doctor"]), doctorController.update);
router.delete("/:id", verifyToken, authorizeRole(["manager", "doctor"]), doctorController.delete);
export default router;
